---
#########################################################################################
# Copyright 2015 Dag Sonstebo
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########################################################################################
#
# CLOUDMONKEY CONFIGURATION PLAYBOOK
#
# Used following CloudStack base install, playbook uses Cloudmonkey to configure
# zone, networks, pods, clusters, XenServer hosts and primary/secondary storage. 
# 
# Prereqs and network topology:
#   - Fully built and running CloudStack management server.
#   - Built XenServer hosts, with cloud-private and cloud-public networks configured.
#   - Prepared NFS primary and secondary storage.
#   - VLAN segregation.
#   - Physical network 1: management and private traffic, tagged cloud-private.
#   - Physical network 2: public traffic, tagged cloud-public.
#
# Update variables and run with:
#
# ansible-playbook -i <inventory_file> --limit=<target_host> cloudmonkey.yml
#
# Playbook will prompt for:
#   - XenServer host password
# 
# v1.0 280115 DS
#########################################################################################
# 
- name: apply CloudStack configuration to all nodes
  hosts: cloudstackmanagement
  sudo: yes
  
  #########################################################################################
  # Vars and vars_prompt
  #  
  vars_prompt:

    - name: "KVMPassword"
      prompt: "KVM host root password"
      private: yes

  vars:

    CMConfig:
      NFSHost: 10.58.58.58
      NFSSecondaryShare: /home/public
      NFSPrimaryShare: /home/pri
      PrimaryStoreName: /home/pri
      ZoneName: FirstZone
      PublicDNS1: 223.5.5.5
      PublicDNS2: 180.76.76.76
      InternalDNS1: 223.5.5.5
      InternalDNS2: 180.76.76.76
      GuestCIDR: 10.0.1.0/24
      NetworkType: Advanced
      Phys1Name: FirstPhysicalNetwork
      Phys1Isolation: VLAN
      Phys1VLANs: 220-250
      Phys1TrafficType1: Management
      Phys1TrafficType1Label: cloudbr0
      Phys1TrafficType2: Guest
      Phys1TrafficType2Label: cloudbr0
      Phys2Name: SecondPhysicalNetwork
      Phys2Isolation: VLAN
      Phys2VLANs: 260-300
      Phys2TrafficType1: Public
      Phys2TrafficType1Label: cloudbr0
      PodName: FirstPod
      PodStartIP: 10.58.58.60
      PodEndIP: 10.58.58.80
      PodNetmask: 255.255.255.0
      PodGateway: 10.58.58.1
      PublicStartIP: 10.58.58.81
      PublicEndIP: 10.58.58.100
      PublicNetmask: 255.255.255.0
      PublicGateway: 10.58.58.1
      ClusterName: FirstCluster
      ClusterHypervisor: kvm
      KVMHostIP: 10.58.58.58
      KVMUsername: root
      KVMPassword: engine123
  
  #########################################################################################
  # Tasks
  #
  tasks:
    #- name: Validate input - KVMServer host password
    #  fail: msg="Missing or incorrect KVM Host password."
    - name: Upgrade cloudmonkey
      shell: easy_install --upgrade pip && pip install --upgrade setuptools && pip install --upgrade distribute && wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python 

    #- name: Validate input - KVMServer host password
    #  fail: msg="Missing or incorrect KVM Host password."
    #  when: KVMPassword is not defined or ( KVMPassword is defined and KVMPassword  == "" )
    #  tags:
    #    - cmconfig

    #######################################################
    # Configure first zone
    #
    - name: Configure zone and add resources
      shell: cloudmonkey create zone name={{ CMConfig.ZoneName }} dns1={{ CMConfig.PublicDNS1 }} dns2={{ CMConfig.PublicDNS2 }} internaldns1={{ CMConfig.InternalDNS1 }} internaldns2={{ CMConfig.InternalDNS2 }} guestcidraddress={{ CMConfig.GuestCIDR }} networktype={{ CMConfig.NetworkType }} localstorageenabled=false | grep ^id | awk '{print $3}'
      register: ZoneID
      tags:
        - cmconfig
  
    #######################################################
    # Create first physical network and traffic types
    #
    - name: Create physical network 1
      shell:  cloudmonkey create physicalnetwork name={{ CMConfig.Phys1Name }} zoneid={{ ZoneID.stdout }} isolationmethods={{ CMConfig.Phys1Isolation }} vlan={{ CMConfig.Phys1VLANs }} | grep ^id | awk '{print $3}'
      register: Phys1ID
      tags:
        - cmconfig
  
    - name: Create traffic type on physical network 1 ({{ CMConfig.Phys1TrafficType1 }})
      shell: cloudmonkey add traffictype physicalnetworkid={{ Phys1ID.stdout }} traffictype={{ CMConfig.Phys1TrafficType1 }} kvmnetworklabel={{ CMConfig.Phys1TrafficType1Label }}
      tags:
        - cmconfig

    - name: Create traffic type on physical network 1 ({{ CMConfig.Phys1TrafficType2 }})
      shell: cloudmonkey add traffictype physicalnetworkid={{ Phys1ID.stdout }} traffictype={{ CMConfig.Phys1TrafficType2 }} kvmnetworklabel={{ CMConfig.Phys1TrafficType2Label }}
      tags:
        - cmconfig
    
    #######################################################
    # Configure VR, VPC VR, LB VM
    #
    - name: Get network service provider ID for VR
      shell: cloudmonkey list networkserviceproviders name=VirtualRouter physicalnetworkid={{ Phys1ID.stdout }} | grep ^id | awk '{print $3}'
      register: Phys1VRID
      tags:
        - cmconfig

    - name: Get VR element
      shell: cloudmonkey list virtualrouterelements nspid={{ Phys1VRID.stdout }} | grep ^id | awk '{print $3}'
      register: Phys1VRElement
      tags:
        - cmconfig

    - name: Enable VR
      shell: cloudmonkey api configureVirtualRouterElement enabled=true id={{ Phys1VRElement.stdout }}
      tags:             
        - cmconfig

    - name: Enable network service provider
      shell: cloudmonkey update networkserviceprovider state=Enabled id={{ Phys1VRID.stdout }}
      tags:
        - cmconfig

    - name: Get network service provider ID VPCR
      shell: cloudmonkey list networkserviceproviders name=VpcVirtualRouter physicalnetworkid={{ Phys1ID.stdout }} | grep ^id | awk '{print $3}'
      register: Phys1VPCVRID
      tags:
        - cmconfig

    - name: Get virtual VPC router element
      shell: cloudmonkey list virtualrouterelements nspid={{ Phys1VPCVRID.stdout }} | grep ^id | awk '{print $3}'
      register: Phys1VPCVRElement
      tags:
        - cmconfig
  
    - name: Enable VPC VR
      shell: cloudmonkey api configureVirtualRouterElement enabled=true id={{ Phys1VPCVRElement.stdout }}
      tags:             
        - cmconfig
  
    - name: Enable network service provider
      shell: cloudmonkey update networkserviceprovider state=Enabled id={{ Phys1VPCVRID.stdout }}
      tags:
        - cmconfig

    - name: Get network service provider ID LBVM
      shell: cloudmonkey list networkserviceproviders name=InternalLbVm physicalnetworkid={{ Phys1ID.stdout }} | grep ^id | awk '{print $3}'
      register: Phys1LBVMID
      tags:
        - cmconfig

    - name: Get LBVM element
      shell: cloudmonkey list internalloadbalancerelements nspid={{ Phys1LBVMID.stdout }} | grep ^id | awk '{print $3}'
      register: Phys1LBVMVRElement
      tags:
        - cmconfig

    - name: Enable LBVM
      shell: cloudmonkey configure internalloadbalancerelement id={{ Phys1LBVMVRElement.stdout }} enabled=true 
      tags:             
        - cmconfig

    - name: Enable network service provider LBVM
      shell: cloudmonkey update networkserviceprovider state=Enabled id={{ Phys1LBVMID.stdout }}
      tags:
        - cmconfig

    - name: Enable physical network 1
      shell: cloudmonkey update physicalnetwork state=Enabled id={{ Phys1ID.stdout }}
      tags:
        - cmconfig

    #######################################################
    # Create physical network 2 and traffic type
    #
    - name: Create physical network 2
      shell:  cloudmonkey create physicalnetwork name={{ CMConfig.Phys2Name }} zoneid={{ ZoneID.stdout }} isolationmethods={{ CMConfig.Phys2Isolation }} vlan={{ CMConfig.Phys2VLANs }} | grep ^id | awk '{print $3}'
      register: Phys2ID
      tags:
        - cmconfig

    - name: Create traffic type on physical network 2 ({{ CMConfig.Phys2TrafficType1 }})
      shell: cloudmonkey add traffictype physicalnetworkid={{ Phys2ID.stdout }} traffictype={{ CMConfig.Phys2TrafficType1 }} kvmnetworklabel={{ CMConfig.Phys2TrafficType1Label }}
      tags:
        - cmconfig

    - name: Add public network 
      shell: cloudmonkey create vlaniprange zoneid={{ ZoneID.stdout }}  startip={{ CMConfig.PublicStartIP }}  endip={{ CMConfig.PublicEndIP }} netmask={{ CMConfig.PublicNetmask }} forvirtualnetwork=true gateway={{ CMConfig.PublicGateway }}  physicalnetworkid={{ Phys2ID.stdout }}
      tags:
        - cmconfig

    - name: Enable physical network 2
      shell: cloudmonkey update physicalnetwork state=Enabled id={{ Phys2ID.stdout }}
      tags:
        - cmconfig

    ########################################################
    # Create pod and cluster
    #
    - name: Create pod in zone 1
      shell: cloudmonkey create pod name={{ CMConfig.PodName }} startip={{ CMConfig.PodStartIP }} endip={{ CMConfig.PodEndIP }} netmask={{ CMConfig.PodNetmask }} gateway={{ CMConfig.PodGateway }}  zoneid={{ ZoneID.stdout }} | grep ^id | awk '{print $3}'
      register: PodID
      tags:
        - cmconfig

    - name: Add cluster in zone 1 / pod 1
      shell: cloudmonkey add cluster podid={{ PodID.stdout }} hypervisor={{ CMConfig.ClusterHypervisor }} clustertype=CloudManaged zoneid={{ ZoneID.stdout }} clustername={{ CMConfig.ClusterName }} | grep ^id | awk '{print $3}'
      register: ClusterID
      tags:
        - cmconfig

    - name: Add XS host
      shell: cloudmonkey add host zoneid={{ ZoneID.stdout }} podid={{ PodID.stdout }}  clusterid={{ ClusterID.stdout }} hypervisor={{ CMConfig.ClusterHypervisor }} username={{ CMConfig.KVMUsername }} password={{ KVMPassword | mandatory }}  url=http://{{ CMConfig.KVMHostIP }}
      tags:
        - cmconfig

    #######################################################
    # Add primary storage
    #
    - name: Add primary storage
      shell: cloudmonkey create storagepool zoneid={{ ZoneID.stdout }} podid={{ PodID.stdout }} clusterid={{ ClusterID.stdout }} name={{ CMConfig.PrimaryStoreName }}  provider=nfs url=nfs://{{ CMConfig.NFSHost }}{{ CMConfig.NFSPrimaryShare }}
      tags:
        - cmconfig

    #######################################################
    # Add secondary storage
    #
    - name: Add secondary storage
      shell: cloudmonkey add secondarystorage zoneid={{ ZoneID.stdout }} url=nfs://{{ CMConfig.NFSHost }}{{ CMConfig.NFSSecondaryShare }}
      tags:
        - cmconfig
    
    #######################################################
    # Enable zone
    - name: Enable zone
      shell: cloudmonkey update zone allocationstate=Enabled id={{ ZoneID.stdout }}
      tags:
        - cmconfig

    #######################################################
    # Change secondary storage download url
    - name: Change secondary storage download url
      shell: cloudmonkey update configuration name=secstorage.allowed.internal.sites value=192.168.0.0/16

    #######################################################
    # Restart the cloudstack-management servie
    - name: Restart cloudstack-management service
      shell: service cloudstack-management restart

    - pause: minutes=2

    #######################################################
    # Create a new service offering
    - name: Create a new service offering
      shell: cloudmonkey create serviceoffering cpunumber=1 cpuspeed=500 displaytext=monkeyking memory=256 name=monkeyking

    #######################################################
    # Register a new template of tinycore.qcow2
    - name: Register the new template of tinycore
      shell: cloudmonkey register template hypervisor=kvm zoneid={{ ZoneID.stdout }} format=qcow2 name=tinycore displaytext=tinycoretemplate ispublic=true ostypeid=11 url=http://192.168.0.79/tiny.qcow2

