---
########################### 1. Install ssh key ##################################

- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: install ssh key
    authorized_key: user=root
                    key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" 
                    state=present

- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: install libselinux-python
    yum: name=libselinux-python state=present

########################### 2. Set the fqdn and hostname ##################################
## todo, how to replace fqdn and hostname with the item in inventory? 

- hosts: cloudstackmanagement
  remote_user: root
  roles:
      - { role: ansible-fqdn, fqdn: "csmgmt.example.com", hostname: "csmgmt" }

########################### 3. Set the ntp ##################################
- hosts: cloudstackmanagement
  remote_user: root
  roles:
      - role: ansible-role-ntp
        ntp_config_server: [2.ubuntu.pool.ntp.org, 1.ubuntu.pool.ntp.org, 3.cn.pool.ntp.org]

########################### 4. Set the SELinux ##################################
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

    - name: Set SELinux to disabled
      selinux: policy=targeted state=disabled

    - name: Disable SELinux for now
      ignore_errors: true
      shell: setenforce 0 


########################### 6. Set the epel Repository ##################################
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

    - name: Install wget/vim
      yum: name={{ item }} state=present
      with_items:
        - wget
        - vim

    - name: Install aliyun's epel instead of the epel repo
      shell: wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-6.repo

    - name: Install EPEL repo / python-pip / vim
      yum: name={{ item }} state=present
      with_items:
        - python-pip

########################### 6.5. Install nfs server and utils ##################################
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

    - name: Make the nfs directory
      shell: mkdir -p /home/public && chmod 777 -R /home/public

- hosts: cloudstackmanagement
  remote_user: root
  roles:
      - role: ansible-role-nfs
        nfs_exports: { "/home/public *(rw,sync,no_root_squash)" }

########################### 7. Install mysql for holding the data ##################################
- hosts: cloudstackmanagement
  remote_user: root

  tasks:

    - name: Install MySQL server
      yum: name=mysql-server state=present
  
    - name: Install MySQL python module
      yum: name=MySQL-python state=present

########################### 8. Configure the database ##################################
# Should only run once. 
    - name: Append CloudStack specific settings to my.cnf
      lineinfile: dest=/etc/my.cnf
                  insertbefore="^\[mysqld_safe\]"
                  line="# CloudStack MySQL settings\\ninnodb_rollback_on_timeout=1\\ninnodb_lock_wait_timeout=600\\nmax_connections={{ MySQLMaxConnections }}\\nlog-bin=mysql-bin\\nbinlog-format = \\'ROW\\'\\n" 
                  state=present


########################### 9. Start service and remove users ##################################
    - name: Start the MySQL daemon 
      service: name=mysqld state=started enabled=true

# Just run once.          
#    - name: Remove anonymous MySQL user for {{ ansible_hostname }}
#      action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
#
#    - name: Remove anonymous MySQL user for {{ ansible_fqdn }}
#      action: mysql_user user="" host="{{ ansible_fqdn }}" state="absent"
#
#    - name: Remove anonymous MySQL user for localhost
#      action: mysql_user user="" state="absent"
#
#    - name: Remove the MySQL test DB
#      action: mysql_db db=test state=absent
#
#    - name: Secure MySQL installation / change root user password
#      mysql_user: login_user=root
#                  login_password=''
#                  name=root
#                  password={{ MySQLPass | mandatory }} 
#                  priv=*.*:ALL,GRANT
#                  host={{ item }}
#      with_items:
#        - "{{ ansible_hostname }}"
#        - "{{ ansible_fqdn }}"
#        - 127.0.0.1
#        - ::1
#        - localhost



########################### 5. Set the Local Repository ##################################
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

    - name: Configure CloudStack repo
      template: src=templates/cloudstack.repo.j2 dest=/etc/yum.repos.d/cloudstack.repo mode=0644

###########################  Install cloudstack management server ##################################
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

    - name: Install CloudStack management server
      yum: name=cloudstack-management state=present

