- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

    - name: Set SELinux to disabled
      selinux: policy=targeted state=disabled

    - name: Disable SELinux for now
      ignore_errors: true
      shell: setenforce 0 
