- hosts: newnode
  roles:
    - role: network
      network_bridge_interfaces:
        - device: cloudbr0
          type: bridge
          address: 10.58.58.58
          netmask: 255.255.255.0
          gateway: 10.58.58.1
          bootproto: static
          stp: "on"
          ports: [eth0]
